// Generated by CoffeeScript 1.3.3
(function() {
  var Piece, clear, context, currentPiece, gameLoop, start;

  start = [3, 0];

  currentPiece = null;

  context = null;

  Piece = (function() {

    function Piece(parts, context) {
      this.parts = parts;
      this.context = context;
      this.x = start[0] * 40 + 10;
      this.y = start[1] * 40 + 10;
    }

    Piece.prototype.draw = function() {
      var part, _i, _len, _ref, _results;
      this.context.clear;
      _ref = this.parts;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        part = _ref[_i];
        this.context.beginPath();
        this.context.rect(this.x, this.y, 40, 40);
        this.context.fillStyle = "#333333";
        _results.push(this.context.fill());
      }
      return _results;
    };

    return Piece;

  })();

  gameLoop = function() {
    clear();
    currentPiece.y += 40;
    return currentPiece.draw();
  };

  clear = function() {
    context.clearRect(10, 10, 280, 360);
    context.beginPath();
    context.rect(10, 10, 280, 360);
    context.fillStyle = "#fff";
    context.fill();
    context.lineWidth = 1;
    context.strokeStyle = "#000";
    return context.stroke();
  };

  window.onload = function() {
    var board, canvas, x, y, _i, _j;
    board = new Array();
    for (x = _i = 0; _i <= 6; x = ++_i) {
      board[x] = new Array();
      for (y = _j = 0; _j <= 8; y = ++_j) {
        board[y] = 0;
      }
    }
    canvas = document.getElementById('canvas');
    context = canvas.getContext('2d');
    clear();
    currentPiece = new Piece([[0, 0]], context);
    currentPiece.draw();
    return setInterval(gameLoop, 1000);
  };

}).call(this);
